#include "stm32g474xx.h"

int main(void)
{
    RCC->AHB2ENR |= RCC_AHB2ENR_GPIOBEN | RCC_AHB2ENR_GPIOEEN | RCC_AHB2ENR_GPIODEN;
    RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;

    SYSCFG->EXTICR[3] |= SYSCFG_EXTICR4_EXTI13_PB;

    EXTI->IMR1 |= EXTI_IMR1_IM13;
    EXTI->FTSR1 |= EXTI_FTSR1_FT13;
    EXTI->RTSR1 |= EXTI_RTSR1_RT13;
    NVIC_EnableIRQ( EXTI15_10_IRQn );

    GPIOB->MODER &= ~GPIO_MODER_MODE13_Msk;

    GPIOE->MODER &= ~GPIO_MODER_MODE5_Msk;
    GPIOE->MODER |= 1 << GPIO_MODER_MODE5_Pos;


    GPIOD->MODER &= ~GPIO_MODER_MODE7_Msk;
    GPIOD->MODER |= 1 << GPIO_MODER_MODE7_Pos;

    while (1)
    {

    }
}

void EXTI15_10_IRQHandler()
{
	if((GPIOB->IDR & GPIO_IDR_ID13) == 0)
	{
		GPIOE->BSRR = GPIO_BSRR_BS5;
						GPIOD->BSRR = GPIO_BSRR_BS7;
	}
	if(GPIOB->IDR & GPIO_IDR_ID13)
	{
	GPIOE->BSRR = GPIO_BSRR_BR5;
					GPIOD->BSRR = GPIO_BSRR_BR7;
	}
  EXTI->PR1 = EXTI_PR1_PIF13;

}


