#include "stm32g474xx.h"

int main(void)
{

    RCC->AHB2ENR |= RCC_AHB2ENR_GPIOBEN | RCC_AHB2ENR_GPIODEN;
    RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;


    SYSCFG->EXTICR[3] |= SYSCFG_EXTICR4_EXTI12_PB | SYSCFG_EXTICR4_EXTI13_PB | SYSCFG_EXTICR4_EXTI14_PB | SYSCFG_EXTICR4_EXTI15_PB;
    EXTI->IMR1 |= EXTI_IMR1_IM12 | EXTI_IMR1_IM13 | EXTI_IMR1_IM14 | EXTI_IMR1_IM15;
    EXTI->FTSR1 |= EXTI_FTSR1_FT12 | EXTI_FTSR1_FT13 | EXTI_FTSR1_FT14 | EXTI_FTSR1_FT15;

    NVIC_EnableIRQ( EXTI15_10_IRQn );

    GPIOB->MODER &= ~(GPIO_MODER_MODE12_Msk | GPIO_MODER_MODE13_Msk | GPIO_MODER_MODE14_Msk | GPIO_MODER_MODE15_Msk);

    GPIOD->MODER &= ~(GPIO_MODER_MODE1_Msk | GPIO_MODER_MODE2_Msk | GPIO_MODER_MODE3_Msk | GPIO_MODER_MODE4_Msk);
    GPIOD->MODER |= 1 << GPIO_MODER_MODE1_Pos | 1 << GPIO_MODER_MODE2_Pos |  1 << GPIO_MODER_MODE3_Pos | 1 << GPIO_MODER_MODE4_Pos;

    while (1)
    {

    }
}

void EXTI15_10_IRQHandler() {
	while ((GPIOB->IDR & GPIO_IDR_ID12) == 0 || (GPIOB->IDR & GPIO_IDR_ID13) == 0 || (GPIOB->IDR & GPIO_IDR_ID14) == 0 || (GPIOB->IDR & GPIO_IDR_ID15) == 0) {
		if ((GPIOB->IDR & GPIO_IDR_ID13) == 0) {
			GPIOD->BSRR = GPIO_BSRR_BS1;
		} else {
			GPIOD->BSRR = GPIO_BSRR_BR1;
		}
		if ((GPIOB->IDR & GPIO_IDR_ID13) == 0) {
			GPIOD->BSRR = GPIO_BSRR_BS2;
		} else {
			GPIOD->BSRR = GPIO_BSRR_BR2;
		}
		if ((GPIOB->IDR & GPIO_IDR_ID14) == 0) {
			GPIOD->BSRR = GPIO_BSRR_BS3;
		} else {
			GPIOD->BSRR = GPIO_BSRR_BR3;
		}
		if ((GPIOB->IDR & GPIO_IDR_ID15) == 0) {
			GPIOD->BSRR = GPIO_BSRR_BS4;
		} else {
			GPIOD->BSRR = GPIO_BSRR_BR4;
		}
	}
	GPIOD->BSRR = GPIO_BSRR_BR1;
		GPIOD->BSRR = GPIO_BSRR_BR2;
		GPIOD->BSRR = GPIO_BSRR_BR3;
		GPIOD->BSRR = GPIO_BSRR_BR4;
	EXTI->PR1 = EXTI_PR1_PIF13;

}
